#include "game.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/garbage.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app.
typedef enum {
  START,
  PLAY,
  WIN,
} GBAState;

int main(void) {
  REG_DISPCNT = MODE3 | BG2_ENABLE;

  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial game state
  GBAState state = START;

  while (1) {
    drawImageDMA(10,20, GARBAGE_WIDTH, GARBAGE_HEIGHT, garbage);
    currentButtons = BUTTONS;  // Load the current state of the buttons

    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
      break;

      case PLAY:
      break;

      case WIN:
      break;
    }
  }

  previousButtons = currentButtons;  // Store the current state of the buttons
  UNUSED(previousButtons);  // You can remove this once previousButtons is used

  return 0;
}
